on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        description: 'Operating System'
        required: true
        default: 'ubuntu-latest'

permissions:
  contents: read

jobs:
  release:
    runs-on: ${{ inputs.runs-on }}
    shell: bash
    steps:
      - run: echo "Hello World"

