name: Build & Test

on:
  workflow_call:
    inputs:
      os:
        type: string
        description: 'Operating System'
        required: true
        default: 'ubuntu-latest'

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure
        shell: bash
        run: mkdir -p ./build

      - name: Create Build files
        shell: bash
        working-directory: ./build
        run: |
          cmake ../ \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++

      - name: Build Binary files
        shell: bash
        working-directory: ./build
        run: cmake --build . -j 4

      - name: Verify Build
        shell: bash
        working-directory: ./build
        run: ./crush --version

  unit-test:
    runs-on: ${{ inputs.os }}
    needs: build
    steps:
      ## actually don't want to do this, we want to pull in the artifacts from the build and run that.
      - name: Checkout repository
        uses: actions/checkout@v4
