name: build-test

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        description: 'Operating System'
        required: true
        default: 'ubuntu-latest'
      compiler:
        type: string
        description: 'Compiler to use'

env:
  CC: ${{ inputs.compiler == 'clang' && 'clang' || 'gcc' }}
  CXX: ${{ inputs.compiler == 'clang' && 'clang++' || 'g++' }}
  BIN_PATH: ${{ inputs.compiler == 'msvc' && './build/Release' || './build' }}
  ARTIFACTS_NAME: ${{ startsWith(inputs.runs-on, 'windows') && 'win32' || (startsWith(inputs.runs-on, 'linux') && 'linux' || 'macos') }}-${{ inputs.compiler }}

jobs:
  build:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup LLVM 14
        uses: rush-lang/setup-llvm-action@v1
        with:
          compiler: ${{ inputs.compiler }}
          llvm-version: 14
          install-prefix: '~/llvm'
      - name: Create build files
        run: >-
          cmake -B build -S .
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_C_COMPILER=$CC
          -DCMAKE_CXX_COMPILER=$CXX
          -DCMAKE_PREFIX_PATH=~/llvm

      - name: Build binary files
        run:
          cmake --build build -j 2 --config Release

      - name: Archive build files
        run: tar -cvf build.tar ./build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACTS_NAME }}
          path: ./build.tar

  unit-test:
    runs-on: ${{ inputs.runs-on }}
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACTS_NAME }}
          path: ./

      - name: Extract build artifacts
        run: tar -xvf build.tar

      - name: Run unit tests
        working-directory: ./build
        run: ctest --parallel 2 --output-on-failure
