name: Check PR

on:
  pull_request:
    branches: [main]

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        compiler: [gcc, clang, msvc]
        exclude:
          - os: windows-latest
            compiler: gcc
          - OS: windows-latest
            compiler: clang
          - os: ubuntu-latest
            compiler: msvc
          - os: ubuntu-latest
            compiler: clang
          - os: macos-latest
            compiler: gcc
          - os: macos-latest
            compiler: msvc
    uses: ./.github/workflows/build-test.yml
    with:
      runs-on: ${{ matrix.os }}
      compiler: ${{ matrix.compiler }}
    secrets: inherit
