name: CI / CD

on:
  push:
    branches: [master]

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    uses: ./.github/workflows/main.yml
    with:
      runs-on: ${{ matrix.os }}
      release: true
    secrets: inherit
