name: linux-gcc

permissions:
  contents: read

on:
  push:
    paths:
      - .github/**
      - external/**
      - '**.hpp'
      - '**.hpp.in'
      - '**.hpp.j2'
      - '**.cpp'
      - '**.cpp.j2'
      - '**.cmake'
      - '**CMakeLists.txt'

jobs:
  linux-gcc:
    uses: ./.github/workflows/build-test.yml
    with:
      runs-on: ubuntu-latest
      compiler: gcc
    secrets: inherit
