permissions:
  contents: read

on: [push, pull_request]

jobs:
  build-test:
    uses: ./.github/workflows/build-test.yml
    with:
      runs-on: macos-latest
      compiler: clang
    secrets: inherit
