name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    uses: ./.github/workflows/build-test.yml
    with:
      runs-on: ${{ matrix.os }}
    secrets: inherit

  release:
    needs: build-test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    uses: ./.github/workflows/release.yml
    with:
      runs-on: ${{ matrix.os }}
    secrets: inherit
