name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  os-matrix:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    uses: ./.github/workflows/common/build-test.yml
    with:
      os: ${{ matrix.os }}
    secrets: inherit
