permissions:
  contents: read # to checkout the repository

on:
  push:
    branches: [main]

jobs:
  linux-gcc:
    uses: ./.github/workflows/build-test.yml
    with:
      runs-on: ubuntu-latest
      compiler: gcc
    secrets: inherit
  win32-msvc:
    uses: ./.github/workflows/build-test.yml
    with:
      runs-on: windows-latest
      compiler: msvc
    secrets: inherit
  macos-clang:
    uses: ./.github/workflows/build-test.yml
    with:
      runs-on: macos-latest
      compiler: clang
    secrets: inherit

  release:
    runs-on: ubuntu-latest
    needs:
      - linux-gcc
      - win32-msvc
      - macos-clang
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to add a comment to a GitHub issue
      pull-requests: write # to be able to comment on released pull requests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts
