name: Release

permissions:
  contents: read # to checkout the repository

on:
  push:
    branches: [main]

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        compiler: [gcc, clang, msvc]
        exclude:
          - os: windows-latest
            compiler: gcc
          - os: ubuntu-latest
            compiler: msvc
          - os: macos-latest
            compiler: msvc
    uses: ./.github/workflows/build-test.yml
    with:
      runs-on: ${{ matrix.os }}
      compiler: ${{ matrix.compiler }}
    secrets: inherit

  release:
    runs-on: ubuntu-latest
    needs: build-test
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to add a comment to a GitHub issue
      pull-requests: write # to be able to comment on released pull requests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts
