name: release

permissions:
  contents: read # to checkout the repository

on:
  workflow_run:
    branches: [main]
    types: [completed]
    workflows:
      - linux-gcc
      - win32-msvc
      - macos-clang

jobs:
  failed:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "The triggering workflow '${{ github.event.workflow_run.name }}' failed."
      - run: exit 1
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ${{ startsWith(github.event.workflow_run.name, 'linux') && 'ubuntu-latest' || startsWith(github.event.workflow_run.name, 'win32') && 'windows-latest' || 'macos-latest' }}
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to add a comment to a GitHub issue
      pull-requests: write # to be able to comment on released pull requests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts
