name: win32-msvc

permissions:
  contents: read

on: [push, pull_request]

jobs:
  win32-msvc:
    uses: ./.github/workflows/build-test.yml
    with:
      runs-on: windows-latest
      compiler: msvc
    secrets: inherit
